apiVersion: apps/v1
kind: Deployment
metadata:
  name: mps-processing
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mps-processing
  template:
    metadata:
      name: mps-processing
      labels:
        app.kubernetes.io/name: mps-processing
    spec:
      containers:
        - name: mps-processing
          image: mps-processing:0.0.1
---
apiVersion: v1
kind: Service
metadata:
  name: mps-processing
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: mps-processing
  ports:
    - port: 8081
      nodePort: 30801