version: "3.3"
services:
  #
  zookeeper:
    image: confluentinc/cp-zookeeper:5.3.1
    expose:
      - 2181
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
  kafka:
    image: confluentinc/cp-kafka:5.3.1
    expose:
      - 9091
    ports:
      - 9092:9092
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_INTER_BROKER_LISTENER_NAME=LISTENER_INTERNAL
      - KAFKA_ADVERTISED_LISTENERS=LISTENER_INTERNAL://kafka:9091,LISTENER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=LISTENER_INTERNAL:PLAINTEXT,LISTENER_EXTERNAL:PLAINTEXT
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    depends_on:
      - zookeeper
  kafdrop:
    image: obsidiandynamics/kafdrop:3.29.0
    ports:
      - 9000:9000
    environment:
      KAFKA_BROKERCONNECT: kafka:9091
    depends_on:
      - kafka
  postgres:
    image: postgres:14.2
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: processing
      POSTGRES_USER: processing
      POSTGRES_PASSWORD: processing
  redis:
    image: redis:6.2.6
    ports:
      - 6379:6379