server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/processing
    username: processing
    password: processing
  redis:
    lettuce:
      pool:
        enabled: true
  kafka:
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: ${spring.application.name}
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
#        max.poll.records: 1
  jpa:
    open-in-view: false
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/auth/realms/master/protocol/openid-connect/certs